.

diff --git a/.github/workflows/checkin.yml b/.github/workflows/checkin.yml
--- a/.github/workflows/checkin.yml
+++ b/.github/workflows/checkin.yml
@@ -1,28 +1,27 @@
 name: checkin
 
-on: 
-- push
-- pull_request
+on:
+  - push
+  - pull_request
 
 jobs:
   checkin:
-
     runs-on: ubuntu-latest
-    
+
     steps:
-    - uses: actions/checkout@v1
-    - name: install
-      run: yarn install
-    - name: build
-      run: yarn build
-    - name: test
-      run: yarn test
-    - name: release
-      run: yarn release    
-    - name: "check for uncommitted changes"
-      # Ensure no changes
-      run: |
-        git add . && git diff --exit-code --stat \
-        || (echo "##[error] found changed files after build. please 'yarn build && npm run format'" \
-                 "and check in all changes" \
-            && exit 1)
+      - uses: actions/checkout@v1
+      - name: install
+        run: yarn install
+      - name: build
+        run: yarn build
+      - name: test
+        run: yarn test
+      - name: release
+        run: yarn release
+      - name: "check for uncommitted changes"
+        # Ensure no changes
+        run: |
+          git add . && git diff --exit-code --stat \
+          || (echo "##[error] found changed files after build. please 'yarn build && npm run format'" \
+                   "and check in all changes" \
+              && exit 1)
