update

diff --git a/.github/workflows/checkin.yml b/.github/workflows/checkin.yml
--- a/.github/workflows/checkin.yml
+++ b/.github/workflows/checkin.yml
@@ -22,7 +22,7 @@ jobs:
         # Ensure no changes
         run: |
           git add .
-          if ! git diff --cached --color=always --stat --exit-code; then
-            echo "::error::Found changed files after build. Please 'yarn build && npm run format' and check in all changes."
+          if ! git diff --cached --color=always --exit-code; then
+            echo "::error::Found changed files after build. Please run 'yarn release' and check in all changes."
             exit 1
           fi
